<div class="bitbucket_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-bitbucket">Destination URL</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-bitbucket', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i>Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http and https URI schemes.</i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbToken">Bitbucket App Password</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbToken', 'Bitbucket App Password', '<a href="https://bitbucket.org/account/settings/app-passwords/new" target="_blank">Create a new one</a>', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbRepo">Account &amp; Repository Name</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbRepo', 'Account / Repository Name', 'ie, leonstafford/wordpress-static-html-plugin'); ?><br>

          <p><i>Repository cannot be empty, just create any file via the Bitbucket UI if needed</i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbBranch">Branch</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbBranch', 'Branch', 'usually \'master\' or \'bb-pages\''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bb_test">Test Bitbucket Settings</label>
        </th>
        <td>
          <button id="bitbucket-test-button" type="button" class="btn-primary button">Test Bitbucket Settings</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
