<div class="bitbucket_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-bitbucket">Destination URL</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-bitbucket', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i>Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.</i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbToken">Personl Access Token</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbToken', 'Bitbucket Personal Access Token', '<a href="https://bitbucket.com/settings/tokens/new" target="_blank">How do I get this?</a>', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbRepo">Account &amp; Repository Name</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbRepo', 'Account / Repository Name', 'ie, leonstafford/wordpress-static-html-plugin'); ?><br>

          <p><i>Repository cannot be empty, just create any file via the Bitbucket UI if needed</i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbBranch">Branch</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbBranch', 'Branch', 'usually \'master\' or \'bb-pages\''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bbPath">Subdirectory</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bbPath', 'Path within repository', 'Usually the repository root (leave this blank) or the \'doc\' folder'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bb_test">Test Bitbucket Settings</label>
        </th>
        <td>
          <button id="bitbucket-test-button" type="button" class="btn-primary button">Test Bitbucket Settings</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
