<div class="bunnycdn_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-bunnycdn">Destination URL</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-bunnycdn', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i>Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http and https URI schemes.</i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnStorageZoneName">Storage Zone</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnStorageZoneName', 'Storage Zone Name', 'ie, mybunnystoragezone. This is where the files will be uploaded to. '); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnStorageZoneAccessKey">Storage Zone Access Key</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnStorageZoneAccessKey', 'Storage Zone Access Key', 'Find in your Storage Zone settings', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnPullZoneID">Pull Zone ID</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnPullZoneID', 'Pull Zone ID', 'Numeric. ie, 1234. This will do a cache purge once all files are transferred', 'number'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnPullZoneAccessKey">Pull Zone Access Key</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnPullZoneAccessKey', 'Pull Zone Access Key', 'Find in your Account settings', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdn_api_host">API Region</label>
        </th>
        <td>
        <?php 

        // TODO: shift to S3 model/helper
        $bunny_regions = [
          "sg.storage.bunnycdn.com" => "Asia Singapore",
          "storage.bunnycdn.com" => "Europe (Falkenstein)",
          "ny.storage.bunnycdn.com" => "US West (New York)",
        ];
        ?>

          <?php $tpl->displaySelectMenu($this, $bunny_regions, 'bunnycdn_api_host', 'API Region', '(BETA)'); ?><br>

          <span class="description">choose the BunnyCDN region for API requests</span>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunny_test">Test BunnyCDN Settings</label>
        </th>
        <td>
          <button id="bunny-test-button" type="button" class="btn-primary button">Test BunnyCDN Settings</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
