<div class="gitlab_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-gitlab">Destination URL</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-gitlab', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i>Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http and https URI schemes.</i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="glToken">Personl Access Token</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'glToken', 'GitLab Personal Access Token', '<a href="https://gitlab.com/profile/personal_access_tokens" target="_blank">Get new one</a>', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="glProject">Project ID</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'glProject', 'Project ID', 'find this in your GitLab > Project > Details page'); ?><br>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="glBranch">Branch</label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'glBranch', 'Branch', 'Usually <code>master</code> for GitLab Pages'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="gl_test">Test GitLab Settings</label>
        </th>
        <td>
          <button id="gitlab-test-button" type="button" class="btn-primary button">Test GitLab Settings</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
