<div class="export_logs" style="display:none;">

<br>

<select id="log_switcher">
    <option value="">Choose a log to view</option>
    <option value="export_log">Export Log</option>
    <option value="crawl_log">Crawl Log</option>
</select>

<button id="reload_log_button" class="button-secondary">(Re)load log</button>



<div id="log_load_progress" class="pulsate-css" style="float:none;display:none;"></div>

<br>
<br>

<textarea id="export_log_textarea" style="width:100%;min-height:300px;" disabled>
Please select a log to view from the menu above
</textarea>


</div> <!-- end advanced settings -->

