<div class="help_troubleshooting" style="display:none;">

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label>Documentation &amp; Tutorials</label>
      </th>
      <td>
        <a href="https://statichtmloutput.com" target="_blank">
          Official documentation and tutorials at statichtmloutput.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-wordpress-alt"></span>
        <label>Ask a WordPress expert</label>
      </th>
      <td>
        <a href="https://wordpress.stackexchange.com" target="_blank">
          https://wordpress.stackexchange.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-groups"></span>
        <label>Community</label>
      </th>
      <td>
        <a href="https://forum.wp2static.com/" target="_blank">
          Our support and development forum
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-format-chat"></span>
        <label>Community</label>
      </th>
      <td>
        <a href="https://join.slack.com/t/statichtmloutput/shared_invite/enQtNDQ4MDM4MjkwNjEwLTVmN2I2MmU4ODI2MWRkNzM4ZGU3YWU4ZGVhMzgwZTc1MDE2OGNmYTFhOGMwM2U0ZTVlYTljYmM2Yjk2ODJlOTk" target="_blank">
          Chat for users & developers via Slack
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-hammer"></span>
        <label>Report a bug</label>
      </th>
      <td>
        <a href="https://github.com/WP2Static/static-html-output-plugin" target="_blank">
          Our project page on GitHub
        </a>
      </td>
    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

