<div class="give_love" style="display:none;">

<p>
This is first and foremost free, <a href="" target="https://github.com/leonstafford/wordpress-static-html-plugin/">open source</a> software, but aiming to cover development, support and promotional costs via <a href="https://statichtmloutput.com" target="_blank">licenses for commercial usage</a>.
</p>

<h2>Other ways to support this plugin</h2>

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-wordpress-alt"></span>
        <label>Leave a review</label>
      </th>
      <td>
        <a href="https://wordpress.org/support/plugin/static-html-output-plugin/reviews/" target="_blank">
          Official WordPress.org reviews for StaticHTMLOutput
        </a>

        <p>Reviews play a large part in helping people decide to try a plugin. Try to include how the plugin helped you solve a particular problem.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label>Documentation</label>
      </th>
      <td>
        <a href="https://github.com/leonstafford/wp-static-site-generator-documentation" target="_blank">
            Help write our documentation
        </a>

        <p>A never-ending, continual improvement process that benefits from any input. Instructions on the linked page. If it's too technical, make contact and we can find another way to get your contributions.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-format-chat"></span>
        <label>Help others</label>
      </th>
      <td>
        <a href="https://statichtmloutput.com/community/" target="_blank">
            Help other users in our forums, StackExchange, GitHub Issues or official WordPress.org plugin support page.
        </a>

        <p>We want to help more people realize the benefits of going static and easing their transition. Be there to help answer questions and support each other.</p>
      </td>
    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

