<div class="processing_settings" style="display:none;">

<table class="form-table">
  <tbody>
      <tr>
        <th scope="row">
          <label>Rewrite Links in source code</label>
        </th>
        <td>
        <p>In order to hide any trace that your site uses WordPress, the following paths will be rewritten. You can leave these default options in, but for more control, you can overwrite them.</p><br>

        <p>Replace, for example, default WordPress paths within the source code</p> <br>

        <p>use the full path, such as:</p>

        <pre>
            wp-content/themes/twentyseventeen/,contents/ui/mytheme/
            wp-includes/,inc/
        </pre>
    
        <i>URLs will be first checked to ensure they are part of this site, not an external WordPress site, which would mess up URLs of linked images, etc</i>

        <br>

<?php
    $default_rewrite_rules = '';
?>

          <textarea class="widefat" name="rewrite_rules" id="rewrite_rules" rows="5" cols="10"><?php echo $this->options->rewrite_rules ? $this->options->rewrite_rules : $default_rewrite_rules;  ?></textarea>
        </td>
    </tr>
    <tr>
        <th scope="row">
          <label>Rename Exported Directories</label>
        </th>
        <td>
        <p>Likely required if doing any URL rewriting above.</p><br>

        <p>Set the source directory, then a comma and the target directory. </p

        <p>
In order to move wp-content/themes/twentyseventeen to contents/ui/mytheme, we'd need:
</p>

<pre>
wp-content,contents
contents/themes,contents/ui
contents/ui/twentyseventeen,contents/ui/mytheme
wp-includes/,inc/
</pre>



         <br>
<?php
    $default_rename_rules = '';
?>

          <textarea class="widefat" name="rename_rules" id="rename_rules" rows="5" cols="10"><?php echo $this->options->rename_rules ? $this->options->rename_rules : $default_rename_rules;  ?></textarea>
        </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="stripping">Remove cruft</label>
      </th>
      <td>

        <?php $tpl->displayCheckbox($this, 'removeConditionalHeadComments', 'Remove conditional comments within HEAD', 'checked'); ?>

        <p>Mostly obsolete, previously used for detecting versions of Internet Explorer and serving different CSS or JS.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeWPMeta', 'Remove WP Meta tags'); ?>

        <p>The <code>&lt;meta&gt; name="generator" content="WordPress 4.9.8" /&gt;</code> type tags.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeWPLinks', 'Remove WP &lt;link&gt; tags'); ?>

        <p>ie, <code>&lt;link& rel="EditURI"...</code> type tags that usually aren't needed.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeHTMLComments', 'Remove HTML comments'); ?>

        <p>ie, <code>&lt;!-- / Yoast SEO plugin. --&gt;</code> type comments that are ridiculously wasting bytes</p><br>
      </td>
    </tr>
  </tbody>
</table>

</div><!-- end processing_setings -->
